##Plot4
#fileUrl1<-"https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
#download.file(fileUrl1,destfile="./data/SSDA.zip",mode="wb")
#dir.create("./data/zipdir")
#unzip("./data/SSDA.zip",exdir="./data/zipdir")
hhpc<-read.table("./data/household_power_consumption.txt",header=T,sep=";",na.string="?")
hhpc1<-subset(hhpc,hhpc$ï..Date=="1/2/2007"| hhpc$ï..Date=="2/2/2007")
hhpc1$DateTime<-strptime(paste(hhpc1$ï..Date,hhpc1$Time),format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2),oma=c(0,0,2,0))
with(hhpc1,{
  plot(hhpc1$DateTime,hhpc1$Global_active_power,type="l",ylab="Global Active Power (kilowatts)",xlab="")
  plot(hhpc1$DateTime,hhpc1$Voltage,type="l",ylab="Voltage",xlab="datetime")
  with(hhpc1,plot(hhpc1$DateTime,hhpc1$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="",col="black"))
  with(hhpc1,lines(hhpc1$DateTime,hhpc1$Sub_metering_2,type="l",col="red"))
  with(hhpc1,lines(hhpc1$DateTime,hhpc1$Sub_metering_3,type="l",col="blue"))
  legend("topright",pch="___",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n")
  plot(hhpc1$DateTime,hhpc1$Global_reactive_power,type="l",ylab="Global reactive Power",xlab="datetime")
  mtext("Plot 4",side=3,line=0,adj=0,outer=T)
})
dev.copy(png,"./data/plot4.png")
dev.off()
